name: StackSpot AI Remote Quick Command Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true

      - name: Check changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
        shell: bash

      - name: Run StackSpot AI Remote Quick Command
        uses: GuillaumeFalourd/stackspot-ai-rqc@v1
        id: rqc
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
          QC_SLUG: jira-task
          INPUT_DATA: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check Remote Quick Command answer
        run: echo ${{ steps.rqc.outputs.rqc_result }}

      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Task
        id: create-jira-task
        uses: atlassian/gajira-create@v3
        with:
          project: "STAC"
          issuetype: "Task"
          summary: "StackSpot AI - DevSecOps"
          description: ${{ fromJson(steps.rqc.outputs.rqc_result) }}

      - name: Log created issue
        run: echo "Issue ${{ steps.create-jira-task.outputs.issue }} was created"