name: 'StackSpot AI Remote Quick Command Action'

description: 'StackSpot AI Remote Quick Command Action'

outputs:
  rqc_result:
    description: "Remote Quick Command answer"
    value: ${{ steps.rqc.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10' 

    - name: Install python libraries 
      run: pip install requests
      shell: bash

    - name: Run StackSpot AI Remote Quick Command
      id: rqc
      run: python3 ${GITHUB_ACTION_PATH}/rqc.py
      shell: bash
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
        CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
        QC_SLUG: ${{ secrets.QC_SLUG }}
        INPUT_DATA: ${{ inputs.INPUT_DATA }}

branding:
    icon: 'terminal'
    color: 'gray-dark'
