name: StackSpot AI Remote Quick Command Action

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true

      - name: Check changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}
        shell: bash

      - uses: GuillaumeFalourd/stackspot-ai-rqc@v1
        id: rqc
        with:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
          QC_SLUG: clean-code-marcel
          INPUT_DATA: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check Remote Quick Command answer
        run: echo ${{ toJSON(steps.rqc.outputs.rqc_result) }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.rqc.outputs.rqc_result != '' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Identified security vulnerabilities through `stackspot-ai-security-action-poc` action:
            ${{ toJSON(steps.rqc.outputs.rqc_result) }}
          reactions: 'eyes'
